env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - airbnb-typescript
  - "prettier"
  - "next/core-web-vitals"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "tsconfig.json"
  ecmaVersion: 2021
plugins:
  - "@typescript-eslint"
  - "prettier"
