import "../styles/globals.css";
import Head from "next/head";
import theme from "@components/theme";

import { ApolloClient, InMemoryCache } from '@apollo/client/core';
import { ApolloProvider } from "@apollo/client/react";
import { ThemeProvider as MuiThemeProvider } from "@material-ui/core/styles";
import { ThemeProvider } from "styled-components";
import { StylesProvider } from '@material-ui/core/styles'
const GQL_URI = 'https://rickandmortyapi.com/graphql';

const client = new ApolloClient( {
    uri: GQL_URI, 
    cache: new InMemoryCache()
})

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <ApolloProvider client={client}>
            <StylesProvider injectFirst>
              <MuiThemeProvider theme={theme}>
                <ThemeProvider theme={theme}>
                  <Component {...pageProps} />
                </ThemeProvider>
              </MuiThemeProvider>
              </StylesProvider>
          </ApolloProvider>
        </div>
      </main>
    </div>
  );
}

export default MyApp;
